"""cards.py - generate dataset cards, model cards, and Kaggle metadata.

All text writers return strings; the CLI writes them to disk. Kaggle tags are
validated against the small taxonomy Kaggle accepts (taxonomy tags only, no free
text), so a release does not get rejected on tags.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Sequence

# Kaggle accepts taxonomy tags only. This is the curated set this toolkit
# allows; the marketing entry uses the first five. Treat the Kaggle UI as the
# source of truth and extend deliberately.
KAGGLE_VALID_TAGS: List[str] = [
    "marketing",
    "nlp",
    "text generation",
    "business",
    "internet",
]


class InvalidKaggleTag(ValueError):
    """Raised when a Kaggle tag is outside the accepted taxonomy."""


def validate_kaggle_tags(tags: Sequence[str]) -> List[str]:
    """Lower-case, de-duplicate, and validate against KAGGLE_VALID_TAGS."""
    cleaned: List[str] = []
    for raw in tags:
        tag = str(raw).strip().lower()
        if not tag:
            continue
        if tag not in KAGGLE_VALID_TAGS:
            raise InvalidKaggleTag(
                "'"
                + tag
                + "' is not an accepted Kaggle taxonomy tag. Valid tags: "
                + ", ".join(KAGGLE_VALID_TAGS)
            )
        if tag not in cleaned:
            cleaned.append(tag)
    return cleaned


def _yaml_front_matter(fields: Dict[str, Any]) -> str:
    """Tiny YAML emitter for the card front matter (scalars + flat lists).

    Avoids a pyyaml dependency for the simple shapes cards need.
    """
    lines: List[str] = ["---"]
    for key, value in fields.items():
        if value is None:
            continue
        if isinstance(value, (list, tuple)):
            if not value:
                continue
            lines.append(key + ":")
            for item in value:
                lines.append("  - " + str(item))
        else:
            lines.append(key + ": " + str(value))
    lines.append("---")
    return "\n".join(lines)


def generate_dataset_card(
    title: str,
    summary: str,
    license: str = "apache-2.0",
    language: str = "en",
    tags: Optional[Sequence[str]] = None,
    source: Optional[str] = None,
    improvement_percent: Optional[float] = None,
    recipe: Optional[Dict[str, Any]] = None,
    row_count: Optional[int] = None,
) -> str:
    """Return a Hugging Face dataset card (README.md with YAML front matter)."""
    front = _yaml_front_matter(
        {
            "license": license,
            "language": [language],
            "tags": list(tags) if tags else None,
            "pretty_name": title,
        }
    )
    body: List[str] = ["", "# " + title, "", summary, ""]
    body.append(
        "Adapted with Adaption Adaptive Data. Card generated by "
        "adaption-kit (community, unofficial)."
    )
    body.append("")
    if improvement_percent is not None:
        body.append("## Evaluation")
        body.append("")
        body.append(
            "Measured quality improvement vs baseline: "
            + str(round(float(improvement_percent), 2))
            + " percent (Adaption get_evaluation, held out set)."
        )
        body.append("")
    if row_count is not None:
        body.append("## Size")
        body.append("")
        body.append("Rows: " + str(row_count))
        body.append("")
    if recipe:
        body.append("## Adaptation recipe")
        body.append("")
        body.append("```json")
        body.append(json.dumps(recipe, indent=2, ensure_ascii=False))
        body.append("```")
        body.append("")
    if source:
        body.append("## Source")
        body.append("")
        body.append(source)
        body.append("")
    body.append("## License")
    body.append("")
    body.append("Released under " + license + ".")
    return front + "\n".join(body) + "\n"


def generate_model_card(
    title: str,
    summary: str,
    base_model: Optional[str] = None,
    license: str = "apache-2.0",
    language: str = "en",
    tags: Optional[Sequence[str]] = None,
    dataset: Optional[str] = None,
    improvement_percent: Optional[float] = None,
    intended_use: Optional[str] = None,
    limitations: Optional[str] = None,
) -> str:
    """Return a Hugging Face model card (README.md with YAML front matter)."""
    fm: Dict[str, Any] = {
        "license": license,
        "language": [language],
        "tags": list(tags) if tags else None,
        "pretty_name": title,
    }
    if base_model:
        fm["base_model"] = base_model
    if dataset:
        fm["datasets"] = [dataset]
    front = _yaml_front_matter(fm)

    body: List[str] = ["", "# " + title, "", summary, ""]
    if base_model:
        body.append("Base model: " + base_model)
        body.append("")
    body.append(
        "Adapted with Adaption Adaptive Data. Card generated by "
        "adaption-kit (community, unofficial)."
    )
    body.append("")
    if improvement_percent is not None:
        body.append("## Evaluation")
        body.append("")
        body.append(
            "Measured quality improvement vs baseline: "
            + str(round(float(improvement_percent), 2))
            + " percent (Adaption get_evaluation, held out set)."
        )
        body.append("")
    body.append("## Intended use")
    body.append("")
    body.append(intended_use or "Describe the intended use of this model here.")
    body.append("")
    body.append("## Limitations")
    body.append("")
    body.append(
        limitations
        or "Adapted data may carry biases from the source corpus. Evaluate before production use."
    )
    body.append("")
    body.append("## License")
    body.append("")
    body.append("Released under " + license + ".")
    return front + "\n".join(body) + "\n"


def generate_kaggle_metadata(
    title: str,
    kaggle_slug: str,
    subtitle: str = "",
    description: str = "",
    tags: Optional[Sequence[str]] = None,
    licenses: Optional[Sequence[str]] = None,
) -> Dict[str, Any]:
    """Build a Kaggle ``dataset-metadata.json`` dict (tags validated).

    ``kaggle_slug`` is ``owner/dataset-name``. Returns a dict; the CLI writes it
    to ``dataset-metadata.json``.
    """
    validated = validate_kaggle_tags(tags) if tags else []
    license_name = (list(licenses)[0] if licenses else "Apache 2.0")
    meta: Dict[str, Any] = {
        "title": title,
        "id": kaggle_slug,
        "subtitle": subtitle,
        "description": description
        or (title + " - adapted with Adaption Adaptive Data via adaption-kit."),
        "licenses": [{"name": license_name}],
        "keywords": validated,
    }
    return meta
